version: '3'

services:
  api-service: 
    container_name: api-service
    build:
      context: api-service
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    
  data-processor: 
    container_name: data-processor
    build:
      context: data-processor
      dockerfile: Dockerfile

  database:
    container_name: database
    image: mongo:5